
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 14 18:15:58 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 46;
  public static final int CONST = 15;
  public static final int SEMI = 41;
  public static final int LPAREN = 5;
  public static final int GREATER = 33;
  public static final int CONTINUE = 20;
  public static final int LESS = 35;
  public static final int MINUS = 27;
  public static final int RPAREN = 6;
  public static final int AND = 37;
  public static final int RECORD = 22;
  public static final int LESSEQUAL = 36;
  public static final int OR = 38;
  public static final int CHECKEQUAL = 31;
  public static final int BOOL = 45;
  public static final int COMMA = 43;
  public static final int INC = 39;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int IF = 24;
  public static final int LSQBRACE = 7;
  public static final int DOT = 44;
  public static final int FINDANY = 49;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 9;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 47;
  public static final int MOD = 30;
  public static final int IDENT = 48;
  public static final int BREAK = 13;
  public static final int VOID = 12;
  public static final int GREATEREQUAL = 34;
  public static final int COLON = 42;
  public static final int FOREACH = 23;
  public static final int LBRACE = 3;
  public static final int ELSE = 25;
  public static final int ENUM = 14;
  public static final int READ = 19;
  public static final int GOTO = 21;
  public static final int WHILE = 17;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int RSQBRACE = 8;
  public static final int DEC = 40;
  public static final int CHECKNOTEQUAL = 32;
  public static final int PRINT = 11;
  public static final int DO = 16;
}

